# Railway Configuration for Matrix Change Detector (Hybrid AI)
# Build from root directory with explicit backend paths

[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "uv run python src/change_detector/server.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 120  # Increased for AI model loading
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8000"
PYTHONPATH = "/app/backend/src" 