[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
buildContext = "backend"

[deploy]
startCommand = "uv run python src/change_detector/server.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8000"
PYTHONPATH = "/app/src" 